---
# curl          - used to send POST commands to the opensim services for testing or info
# xmmlib-utils  - to format the output of the POST commands
# tree          - to pringt a directory tree
# git           - to get the opensim binaries and to do version control on Ansible playbooks and roles

- name: install helper tools
  apt: 
    name: ['curl', 'xmllib2-utils', 'tree', 'git', 'htop', 'python3-pip', 'libssl-dev']
    state: present
  tags: ['packages']

- name: update apt cache for pip3
  apt: update_cache=yes

- name: install testing tools
  block:
    - name: install lint tools
      pip:
        name: ['yamllint', 'setuptools', 'ansible-lint', 'molecule']
        state: present
        executable: /usr/bin/pip3
  
  tags: ['packages']
