---
- name: install helper tools
  apt: 
    name: ['curl', 'tree', 'screen', 'git', 'vsftpd', 'python3-pip', 'libssl-dev']
    state: present
  notify: restart vsftpd
  tags: ['packages']

- name: update apt cache for pip3
  apt: update_cache=yes

- name: install testing tools
  block:
    - name: install lint tools
      pip:
        name: ['yamllint', 'setuptools', 'ansible-lint', 'molecule']
        state: present
        executable: /usr/bin/pip3
  
  tags: ['packages']
